packages:
    - packages/*
    - playground

blockExoticSubdeps: true

catalog:
    "@types/node": ^24.11.0
    astro: ^5.18.0
    typescript: ^5.9.3

disallowWorkspaceCycles: true

failIfNoMatch: true

ignoreWorkspaceRootCheck: true

minimumReleaseAge: 4320

onlyBuiltDependencies:
    - esbuild
    - lefthook
    - sharp

trustPolicy: no-downgrade

trustPolicyExclude:
    - vite@6.4.1
    - chokidar@4.0.3
